import { ExportMap } from "ts-protoc-gen/lib/ExportMap"
import { Printer } from "ts-protoc-gen/lib/Printer"
import { CodePrinter } from "ts-protoc-gen/lib/CodePrinter"
import { FileDescriptorProto } from "google-protobuf/google/protobuf/descriptor_pb"
import { CodeGeneratorResponse } from "google-protobuf/google/protobuf/compiler/plugin_pb"
import { createFile, RPCMethodDescriptor, RPCDescriptor, GrpcServiceDescriptor } from "ts-protoc-gen/lib/service/common"
import { printRpcDescriptor } from "./shared"

export function generateServerRpcService(
  filename: string,
  descriptor: FileDescriptorProto,
  exportMap: ExportMap
): CodeGeneratorResponse.File[] {
  return [createFile(generateServerTypeScriptDefinition(descriptor, exportMap), `${filename}_server.ts`)]
}

function generateServerTypeScriptDefinition(fileDescriptor: FileDescriptorProto, exportMap: ExportMap): string {
  const serviceDescriptor = new GrpcServiceDescriptor(fileDescriptor, exportMap)
  const printer = new Printer(0)

  // Header.
  printer.printLn(`// AUTOGENERATED, DO NOT EDIT`)
  printer.printLn(`// Type definitions for server implementations of ports.`)

  printer.printLn(`// package: ${serviceDescriptor.packageName}`)
  printer.printLn(`// file: ${serviceDescriptor.filename}`)
  printer.printEmptyLn()

  if (serviceDescriptor.services.length === 0) {
    return printer.getOutput()
  }

  // Import statements.
  serviceDescriptor.imports.forEach((importDescriptor) => {
    printer.printLn(`import * as ${importDescriptor.namespace} from "${importDescriptor.path}";`)
  })
  printer.printLn(`import { RpcServerPort } from "@dcl/rpc";`)
  printer.printLn(`import * as codegen from "@dcl/rpc/dist/codegen";`)
  printer.printEmptyLn()

  // Services.
  serviceDescriptor.services.forEach((service) => {
    printRpcDescriptor(service, printer)

    printer.printLn(
      `export type ${service.name}ModuleInitializator = (port: RpcServerPort) => Promise<${service.name}> | ${service.name}`
    )
    printer.printEmptyLn()
    printer.printLn(
      `export function register${service.name}(port: RpcServerPort, moduleInitializator: ${service.name}ModuleInitializator): void {`
    )

    printer.printLn(`  port.registerModule("BookService", async port => {`)
    printer.printLn(`    const mod = await moduleInitializator(port);`)

    printer.printLn(`    return {`)

    service.methods.forEach((method) => {
      let fun = method.responseStream ? "codegen.serverProcedureStream" : "codegen.serverProcedureUnary"

      printer.printIndentedLn(
        `    ${JSON.stringify(method.nameAsPascalCase)}: ${fun}(mod[${JSON.stringify(method.nameAsPascalCase)}].bind(mod), ${JSON.stringify(method.nameAsPascalCase)}, ${
          method.requestType
        }, ${method.responseType}),`
      )
    })

    printer.printLn(`    }`)
    printer.printLn(`  })`)

    printer.printLn(`}`)
    printer.printEmptyLn()
  })

  return printer.getOutput()
}
